# fly.toml app configuration file generated for clubmaster-backend on 2023-11-25T11:49:51+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clubmaster-backend"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
